#!/usr/bin/env node

import assert from 'node:assert/strict';
import fs from 'node:fs';
import {
  ADAPTIVE_TIME_SCALE_VERSION,
  activityRangeLimitMinutes,
  buildSceneMomentumDirective,
  classifySceneIntent,
  deriveSceneDelta,
  isRequestedScheduledActivity,
  nextScheduleBoundaryMinutes,
  scheduleBoundaryLimitMinutes,
} from '../../lib/scene-momentum.js';

assert.equal(ADAPTIVE_TIME_SCALE_VERSION, '2.0');

const dialogue = classifySceneIntent('아르테미스와 대화한다.', { location:'A동 복도' });
assert.equal(dialogue.kind, 'dialogue');
assert.equal(dialogue.timeProfile, 'dialogue');
assert.deepEqual(dialogue.suggestedAdvanceMinutes, [2, 10]);
assert.equal(dialogue.compression, true);
assert.equal(classifySceneIntent('10시에 에밀리와 면담을 한다.', { location:'상담실',currentTime:'09:00' }).kind,'dialogue','object-marked 면담 must use the dialogue profile');
assert.equal(classifySceneIntent('에밀리와 대화를 한다.', { location:'상담실' }).kind,'dialogue','object-marked 대화 must remain a committed dialogue action');
assert.deepEqual(classifySceneIntent('회의를 1시간 동안 한다.', { location:'회의실' }).suggestedAdvanceMinutes,[60,60],'a duration between a dialogue object and verb must remain exact');
for(const action of ['에밀리가 잠을 잔다.','에밀리가 기다린다.','에밀리가 회의를 한다.','에밀리가 검술을 훈련한다.','에밀리가 도서관으로 간다.'])assert.equal(classifySceneIntent(action).kind,'generic',`a third-party subject must not execute a PC timed action: ${action}`);
assert.equal(classifySceneIntent('에밀리와 아르테미스가 잠을 잔다.').kind,'generic','a coordinated third-party subject must not execute PC downtime');
assert.equal(classifySceneIntent('에밀리가 한 시간 훈련하고 잠을 잔다.').kind,'generic','a leading third-party subject must carry across its compound action');
assert.equal(classifySceneIntent('에밀리가 한 시간 훈련하고 나는 잠을 잔다.').kind,'downtime','an explicit terminal first-person subject must override an earlier NPC subject');
assert.equal(classifySceneIntent('누군가 “죽이겠다”고 외치는 소리를 듣고 에밀리가 잠을 잔다.').kind,'generic','an attributed report must not hide an explicit third-party terminal subject');
assert.equal(classifySceneIntent('카인이 잠을 잔다.',{actorName:'카인'}).kind,'downtime','the actual player name must remain a valid explicit subject');
assert.deepEqual(classifySceneIntent('기숙사에서 카인이 8시간 잠을 잔다.',{actorName:'카인'}).suggestedAdvanceMinutes,[480,480],'a leading location adjunct must not hide the saved PC subject');
assert.deepEqual(classifySceneIntent('조용히 카인이 8시간 잠을 잔다.',{actorName:'카인'}).suggestedAdvanceMinutes,[480,480],'a leading manner adjunct must not hide the saved PC subject');
assert.deepEqual(classifySceneIntent('몸이 피곤해서 8시간 잠을 잔다.').suggestedAdvanceMinutes,[480,480],'a causal-clause subject must not become the omitted subject of the terminal PC action');
assert.deepEqual(classifySceneIntent('날씨가 좋아서 1시간 동안 훈련한다.').suggestedAdvanceMinutes,[60,60],'an environmental causal-clause subject must not block a terminal PC training action');
assert.equal(classifySceneIntent('몸이 피곤해서 에밀리가 8시간 잠을 잔다.').kind,'generic','an explicit third-party subject in the terminal causal tail must remain third-party');
const namedActorDelta=deriveSceneDelta({saveState:{pc:{name:'카인'},world:{location:'기숙사',time:'22:00'}},action:'카인이 8시간 잠을 잔다.',turn:{state_delta:{advance_minutes:480},choices:[]}});
assert.equal(namedActorDelta.intent,'downtime','runtime momentum must classify the saved player name consistently');
assert.equal(namedActorDelta.target,2,'saved-name downtime must retain the downtime State Delta target');
assert.deepEqual(classifySceneIntent('에밀리와는 1시간 동안 대화를 한다.').suggestedAdvanceMinutes,[60,60],'a comitative topic adjunct must not be mistaken for a third-party subject');
assert.deepEqual(classifySceneIntent('에밀리에게는 1시간 동안 설명을 한다.').suggestedAdvanceMinutes,[60,60],'a dative topic adjunct must not be mistaken for a third-party subject');
assert.equal(classifySceneIntent('에밀리와는 아르테미스가 1시간 동안 대화를 한다.').kind,'generic','skipping an adjunct must still preserve a following explicit third-party subject');

for(const [action,kind] of [
  ['1시간 동안 훈련하겠다.','training'],['1시간 동안 훈련할게.','training'],
  ['수업을 듣겠다.','class-attendance'],['수업을 들을게.','class-attendance'],
  ['8시간 잠을 자겠다.','downtime'],['8시간 잠을 잘게.','downtime'],
  ['30분 기다리겠다.','wait'],['30분 기다릴게.','wait'],
  ['20분 동안 식사하겠다.','meal'],['20분 동안 식사할게.','meal'],
  ['10분 동안 대화하겠다.','dialogue'],['10분 동안 대화할게.','dialogue'],
])assert.equal(classifySceneIntent(action).kind,kind,`a committed future-tense action must retain its timed profile: ${action}`);
assert.deepEqual(classifySceneIntent('1시간 동안 훈련하겠다.').suggestedAdvanceMinutes,[60,60],'겠다 training must preserve its exact duration');
assert.deepEqual(classifySceneIntent('8시간 잠을 잘게.').suggestedAdvanceMinutes,[480,480],'할게 sleep must preserve its exact duration');

const directQuestion = classifySceneIntent('아르테미스에게 오리엔테이션이 끝났느냐고 묻는다?', { location:'A동 복도' });
assert.equal(directQuestion.kind, 'decision-sensitive', 'a direct question must retain same-moment player sovereignty');
assert.equal(directQuestion.minAdvanceMinutes, 0);

const meal = classifySceneIntent('점심 식사를 한다.', { location:'식당' });
assert.equal(meal.kind, 'meal');
assert.deepEqual(meal.suggestedAdvanceMinutes, [20, 45]);

const explicitMeal = classifySceneIntent('한 시간 동안 점심 식사를 한다.', { location:'식당' });
assert.equal(explicitMeal.explicitDurationMinutes, 60);
assert.deepEqual(explicitMeal.suggestedAdvanceMinutes, [60, 60]);
assert.deepEqual(classifySceneIntent('점심을 한 시간 동안 먹는다.', { location:'식당' }).suggestedAdvanceMinutes, [60, 60], 'object-duration-verb meal order must honor the explicit duration');
for(const food of ['빵','스테이크']){
  const timedFood=classifySceneIntent(`30분 동안 ${food}을 먹는다.`,{location:'식당'});
  assert.equal(timedFood.kind,'meal',`a timed food-object action must retain the meal profile: ${food}`);
  assert.equal(timedFood.explicitDurationMinutes,30,`a timed food-object action must retain its declared duration: ${food}`);
  assert.deepEqual(timedFood.suggestedAdvanceMinutes,[30,30],`a timed food-object action must advance exactly as declared: ${food}`);
}
assert.deepEqual(classifySceneIntent('빵을 30분 동안 먹는다.',{location:'식당'}).suggestedAdvanceMinutes,[30,30],'object-first timed eating must retain the same exact meal duration');
assert.equal(classifySceneIntent('에밀리가 30분 동안 빵을 먹는다.',{location:'식당'}).kind,'generic','a timed food object must not execute a third-party meal as the PC');
assert.equal(classifySceneIntent('30분 후에 빵을 먹는다.',{location:'식당'}).kind,'generic','a future eating start without a declared eating duration must not become a timed meal');
const scheduledFood=classifySceneIntent('오전 10시에 빵을 먹는다.',{location:'식당',currentTime:'08:00'});
assert.equal(scheduledFood.kind,'meal','a food-object action with an authoritative clock must use the meal profile');
assert.equal(scheduledFood.scheduledStartOffsetMinutes,120,'a scheduled food-object meal must retain its real start offset');
assert.deepEqual(scheduledFood.suggestedAdvanceMinutes,[140,165],'scheduled food-object eating must include its wait and natural meal duration');

const training = classifySceneIntent('검술을 훈련한다.', { location:'훈련장' });
assert.equal(training.kind, 'training');
assert.deepEqual(training.suggestedAdvanceMinutes, [30, 120]);

const explicitTraining = classifySceneIntent('45분 동안 마법을 연습한다.', { location:'훈련장' });
assert.equal(explicitTraining.explicitDurationMinutes, 45);
assert.deepEqual(explicitTraining.suggestedAdvanceMinutes, [45, 45]);
const rangedTraining=classifySceneIntent('1시간에서 2시간 동안 훈련한다.', { location:'훈련장' });
assert.equal(rangedTraining.explicitDurationMinutes,null,'duration range endpoints must not be summed into one exact duration');
assert.deepEqual(rangedTraining.explicitDurationRangeMinutes,[60,120],'the declared training duration range must remain explicit');
assert.equal(rangedTraining.minAdvanceMinutes,60,'the lower range endpoint must be the deterministic minimum');
assert.deepEqual(rangedTraining.suggestedAdvanceMinutes,[60,120],'the time guide must retain both range endpoints without summing them');
assert.match(buildSceneMomentumDirective({action:'1시간에서 2시간 동안 훈련한다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'훈련장'}}}),/EXPLICIT_DURATION_RANGE=60-120min/,'the model must receive the declared range as a range');
assert.deepEqual(classifySceneIntent('30분~1시간 동안 기다린다.').suggestedAdvanceMinutes,[30,60],'tilde-separated duration ranges must also retain their endpoints');
const sharedHourRange=classifySceneIntent('1~2시간 동안 훈련한다.', { location:'훈련장' });
assert.equal(sharedHourRange.explicitDurationMinutes,null,'a shared-unit hour range must not collapse to its upper endpoint');
assert.deepEqual(sharedHourRange.explicitDurationRangeMinutes,[60,120],'shared-unit hour shorthand must retain both endpoints');
assert.deepEqual(sharedHourRange.suggestedAdvanceMinutes,[60,120],'shared-unit hour shorthand must bound the time guide');
assert.deepEqual(classifySceneIntent('30~60분 동안 기다린다.').suggestedAdvanceMinutes,[30,60],'shared-unit minute shorthand must retain both endpoints');
const zeroMinimumWait=classifySceneIntent('0분에서 10분 동안 기다린다.');
assert.equal(zeroMinimumWait.kind,'wait','a zero-minimum explicit range must retain its timed intent');
assert.deepEqual(zeroMinimumWait.explicitDurationRangeMinutes,[0,10],'a zero-minimum explicit range must retain its positive lookahead');
assert.deepEqual(zeroMinimumWait.suggestedAdvanceMinutes,[0,10],'a zero-minimum wait may compress anywhere inside its declared range');
assert.equal(activityRangeLimitMinutes(zeroMinimumWait),10,'consequence lookahead must use the positive range maximum even when its floor is zero');
assert.deepEqual(classifySceneIntent('문 앞에서는 기다리지 않고 로비에서 1시간 동안 기다린다.').suggestedAdvanceMinutes,[60,60],'a negated earlier wait must not cancel a committed terminal wait');
assert.deepEqual(classifySceneIntent('피로가 풀리도록 8시간 동안 잠을 잔다.').suggestedAdvanceMinutes,[480,480],'a subordinate purpose subject must not replace the omitted PC sleep subject');
assert.deepEqual(classifySceneIntent('친구가 올 때까지 1시간 동안 기다린다.').suggestedAdvanceMinutes,[60,60],'a subordinate arrival subject must not replace the omitted PC wait subject');
assert.deepEqual(classifySceneIntent('배가 고프므로 30분 동안 식사를 한다.').suggestedAdvanceMinutes,[30,30],'a subordinate cause subject must not replace the omitted PC meal subject');
assert.deepEqual(classifySceneIntent('훈련을 1시간부터 2시간까지 한다.').suggestedAdvanceMinutes,[60,120],'object-marked from/to duration ranges must remain bounded ranges');
const rangedFutureStart=classifySceneIntent('1시간에서 2시간 후에 훈련한다.',{currentTime:'09:00'});
assert.equal(rangedFutureStart.explicitDurationRangeMinutes,null,'a future start window must not become an activity duration range');
assert.equal(rangedFutureStart.scheduledStartOffsetMinutes,120,'the terminal relative start qualifier must remain the selected start offset');
assert.equal(classifySceneIntent('10분 전에 배운 동작을 훈련한다.').explicitDurationMinutes, null, 'historical time must not become a training duration');
assert.equal(classifySceneIntent('10분 정도 전에 시작한 훈련을 계속한다.').explicitDurationMinutes,null,'an approximately qualified historical offset must not become training duration');
assert.deepEqual(classifySceneIntent('한 시간 가량 후에 검술을 훈련한다.',{currentTime:'09:00'}).suggestedAdvanceMinutes,[90,180],'an approximately qualified future offset must remain a start delay plus the natural training range');
const approximateFutureRange=classifySceneIntent('1시간에서 2시간 정도 후에 검술을 훈련한다.',{currentTime:'09:00'});
assert.equal(approximateFutureRange.explicitDurationMinutes,null,'an approximate future start range must not leak its lower bound into activity duration');
assert.deepEqual(approximateFutureRange.suggestedAdvanceMinutes,[150,240],'an approximate future start range must use its upper start offset plus the natural training range');
assert.equal(classifySceneIntent('한 시간 후에 검술을 훈련한다.').explicitDurationMinutes, null, 'future start time must not become a training duration');
assert.equal(classifySceneIntent('10분 전에 배운 동작을 한 시간 동안 훈련한다.').explicitDurationMinutes, 60, 'a historical reference must not hide a separate explicit activity duration');
assert.equal(classifySceneIntent('한 시간 훈련하고 20분 쉰다.').explicitDurationMinutes, 20, 'a terminal rest must use only the duration attached to that rest clause');
assert.deepEqual(classifySceneIntent('30분 동안 훈련한 뒤 잠을 잔다.').suggestedAdvanceMinutes, [270, 510], 'an explicit preceding training duration must be added to the terminal sleep range');
const compoundExplicitSleep=classifySceneIntent('1시간 동안 훈련을 하고 8시간 동안 잠을 잔다.');
assert.equal(compoundExplicitSleep.explicitDurationMinutes,480,'the terminal explicit sleep duration must remain separately identifiable');
assert.equal(compoundExplicitSleep.precedingActivityMinutes,60,'the committed preceding training duration must be retained');
assert.deepEqual(compoundExplicitSleep.suggestedAdvanceMinutes,[540,540],'compound explicit activities must use their full declared total duration');
const scheduledPrecedingClassSleep=classifySceneIntent('오전 10시에 1시간 동안 수업을 듣고 8시간 동안 잠을 잔다.',{currentTime:'08:00'});
assert.equal(scheduledPrecedingClassSleep.precedingActivityMinutes,180,'a preceding scheduled class must include the wait until its fixed start plus its duration');
assert.deepEqual(scheduledPrecedingClassSleep.suggestedAdvanceMinutes,[660,660],'terminal sleep timing must include the preceding scheduled start delay');
assert.deepEqual(classifySceneIntent('2시간 후에 1시간 동안 수업을 듣고 8시간 동안 잠을 잔다.').suggestedAdvanceMinutes,[660,660],'a relative start delay on a preceding clause must contribute to the full compound timeline');
const untimedCompoundSleep=classifySceneIntent('훈련하고 8시간 동안 잠을 잔다.');
assert.deepEqual(untimedCompoundSleep.precedingActivityRangeMinutes,[30,120],'an untimed preceding training activity must retain its bounded profile');
assert.deepEqual(untimedCompoundSleep.suggestedAdvanceMinutes,[510,600],'terminal explicit sleep must include the natural range of an untimed preceding training action');
assert.deepEqual(classifySceneIntent('도서관에 가서 8시간 동안 잠을 잔다.').suggestedAdvanceMinutes,[483,510],'a recognized untimed preceding trip must contribute a bounded local travel range');
assert.deepEqual(classifySceneIntent('아르테미스가 와서 나는 8시간 동안 잠을 잔다.').suggestedAdvanceMinutes,[480,480],'an NPC arrival connector must not become player travel time');
const rangedCompoundSleep=classifySceneIntent('1시간에서 2시간 동안 훈련을 하고 8시간 동안 잠을 잔다.');
assert.deepEqual(rangedCompoundSleep.precedingActivityRangeMinutes,[60,120],'a preceding activity range must retain both endpoints');
assert.deepEqual(rangedCompoundSleep.suggestedAdvanceMinutes,[540,600],'a preceding activity range must offset the terminal activity with separate lower and upper bounds');
assert.deepEqual(classifySceneIntent('훈련을 1시간에서 2시간 동안 하고 8시간 동안 잠을 잔다.').suggestedAdvanceMinutes,[540,600],'a duration between the preceding activity object and connector must remain scoped to that activity');
const compoundZeroSleep=classifySceneIntent('1시간 동안 훈련을 하고 0분 동안 잠을 잔다.');
assert.equal(compoundZeroSleep.explicitDurationMinutes,0,'the terminal zero duration must remain visible');
assert.equal(compoundZeroSleep.minAdvanceMinutes,60,'the full turn duration must retain the completed preceding hour');
const namedActorZeroTraining=classifySceneIntent('카인이 0분 동안 훈련한다.',{actorName:'카인'});
assert.equal(namedActorZeroTraining.kind,'training','the saved PC name must remain first-party in a zero-time action');
assert.equal(namedActorZeroTraining.explicitDurationMinutes,0,'a named-PC zero-time action must reach downstream freeze guards');
const compoundExplicitDirective=buildSceneMomentumDirective({action:'1시간 동안 훈련을 하고 8시간 동안 잠을 잔다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'기숙사'}}});
assert.match(compoundExplicitDirective,/PRECEDING_ACTIVITY_DURATION=60min/,'the model directive must expose the preceding activity duration');
assert.match(compoundExplicitDirective,/사용자가 540분을 직접 지정했다\(앞선 행동 60분 포함\)/,'the explicit-duration rule must describe the full compound total without contradicting TIME_GUIDE');
const rangedCompoundDirective=buildSceneMomentumDirective({action:'1시간에서 2시간 동안 훈련을 하고 8시간 동안 잠을 잔다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'기숙사'}}});
assert.match(rangedCompoundDirective,/PRECEDING_ACTIVITY_DURATION_RANGE=60-120min/,'the directive must expose a preceding activity range without collapsing it');
assert.match(rangedCompoundDirective,/사용자가 540-600분을 직접 지정했다\(앞선 행동 60-120분 포함\)/,'the directive must describe the full compound range');
assert.equal(classifySceneIntent('한 시간 동안 친구하고 대화한다.').explicitDurationMinutes, 60, 'the comitative 하고 particle must not be mistaken for an activity boundary');

const classAttendance = classifySceneIntent('강의에 참석한다.', { location:'강의실' });
assert.equal(classAttendance.kind, 'class-attendance');
assert.deepEqual(classAttendance.suggestedAdvanceMinutes, [45, 120]);

const explicitClass = classifySceneIntent('두 시간 동안 수업을 듣는다.', { location:'강의실' });
assert.equal(explicitClass.explicitDurationMinutes, 120);
assert.deepEqual(explicitClass.suggestedAdvanceMinutes, [120, 120]);
assert.deepEqual(classifySceneIntent('수업을 두 시간 동안 듣는다.', { location:'강의실' }).suggestedAdvanceMinutes, [120, 120], 'object-duration-verb class order must honor the explicit duration');
assert.equal(classifySceneIntent('10시 30분에 수업을 듣는다.', { location:'강의실' }).explicitDurationMinutes, null, 'a clock minute component must not become an activity duration');
assert.deepEqual(classifySceneIntent('10시 30분에 수업을 한 시간 동안 듣는다.', { location:'강의실' }).suggestedAdvanceMinutes, [60, 60], 'masking a clock must preserve a separate explicit activity duration');
const futureClockClass=classifySceneIntent('10시 30분에 수업을 듣는다.', { location:'여관',currentTime:'07:40' });
assert.equal(futureClockClass.scheduledStartOffsetMinutes,170,'a future clock must become a start offset, not a duration');
assert.deepEqual(futureClockClass.suggestedAdvanceMinutes,[215,290],'scheduled activity time must include waiting until the start plus the class duration');
assert.deepEqual(classifySceneIntent('10시 30분에 수업을 한 시간 동안 듣는다.', { location:'여관',currentTime:'07:40' }).suggestedAdvanceMinutes,[230,230],'a separate explicit duration must be added after the scheduled start');
const compoundClockClass=classifySceneIntent('9시에 아침을 먹고 10시에 수업을 듣는다.', { location:'여관',currentTime:'08:00' });
assert.equal(compoundClockClass.scheduledStartOffsetMinutes,120,'a terminal class must bind to its own clock rather than an earlier compound meal clock');
assert.deepEqual(compoundClockClass.suggestedAdvanceMinutes,[165,240],'the terminal activity clock offset must be added to the class duration range');
assert.equal(classifySceneIntent('내일 9시에 아침을 먹고 10시에 수업을 듣는다.', { location:'여관',currentTime:'08:00' }).scheduledStartOffsetMinutes,null,'scoping to the terminal activity must not collapse an inherited next-day compound clock onto today');
assert.deepEqual(classifySceneIntent('10:30에 수업을 듣는다.', { location:'여관',currentTime:'07:40' }).suggestedAdvanceMinutes,[215,290],'colon clock notation must use the same scheduled-start semantics');
assert.equal(classifySceneIntent('오늘 오후 3시 반에 수업을 듣는다.', { location:'강의실',currentTime:'14:00' }).scheduledStartOffsetMinutes,90,'the 시 반 clock form must normalize to thirty minutes past the hour');
const intervalClockClass=classifySceneIntent('10시 30분부터 11시 30분까지 수업을 듣는다.', { location:'여관',currentTime:'07:40' });
assert.equal(intervalClockClass.explicitDurationMinutes,60,'an explicit start-to-end clock interval must derive the activity duration');
assert.deepEqual(intervalClockClass.suggestedAdvanceMinutes,[230,230],'an explicit clock interval must include the wait to start and end at the requested clock');
assert.deepEqual(classifySceneIntent('오늘 10시부터 11시까지 수업을 듣는다.',{location:'강의실',currentTime:'10:30'}).suggestedAdvanceMinutes,[30,30],'an in-progress clock interval must stop at its declared endpoint');
assert.deepEqual(classifySceneIntent('자정부터 오전 2시까지 잠을 잔다.',{location:'개인실',currentTime:'01:00'}).suggestedAdvanceMinutes,[60,60],'a named-midnight interval already in progress must use only its remaining time');
const pastClockInterval=classifySceneIntent('오늘 10시부터 11시까지 수업을 듣는다.',{location:'강의실',currentTime:'11:30'});
assert.equal(pastClockInterval.explicitDurationMinutes,0,'an entirely past clock interval must be recognized as having no remaining duration');
assert.deepEqual(pastClockInterval.suggestedAdvanceMinutes,[0,0],'an entirely past interval must not replay from the current moment');
const elapsedTodayTraining=classifySceneIntent('오늘 오전 1시에 훈련한다.',{location:'훈련장',currentTime:'09:00'});
assert.equal(elapsedTodayTraining.kind,'decision-sensitive','an explicitly elapsed today start must not execute as an immediate activity');
assert.equal(elapsedTodayTraining.timeProfile,'elapsed-scheduled-start','an elapsed today start must retain its rejection reason');
assert.deepEqual(elapsedTodayTraining.suggestedAdvanceMinutes,[0,0],'rejecting an elapsed today start must preserve the current moment');
assert.match(buildSceneMomentumDirective({action:'오늘 오전 1시에 훈련한다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'훈련장'}}}),/ELAPSED START 규칙/,'the model must be told not to replay or roll over an elapsed today start');
assert.deepEqual(classifySceneIntent('22시부터 2시까지 잠을 잔다.', { location:'개인실',currentTime:'20:00' }).suggestedAdvanceMinutes,[360,360],'an unmarked 24-hour interval ending before its start must cross midnight');
assert.deepEqual(classifySceneIntent('오후 11시부터 자정까지 잠을 잔다.', { location:'개인실',currentTime:'22:00' }).suggestedAdvanceMinutes,[120,120],'a named midnight endpoint must produce an exact interval plus its start wait');
assert.deepEqual(classifySceneIntent('자정부터 오전 2시까지 잠을 잔다.', { location:'개인실',currentTime:'22:00' }).suggestedAdvanceMinutes,[240,240],'a named midnight start must remain available to interval parsing');
assert.equal(classifySceneIntent('10시 30분에 수업을 듣는다.', { location:'강의실',currentTime:'12:00' }).scheduledStartOffsetMinutes,null,'an already-past ambiguous clock must not silently roll into the next day');
const nextDayClass=classifySceneIntent('내일 10시 30분에 수업을 듣는다.', { location:'여관',currentTime:'07:40' });
assert.equal(nextDayClass.scheduledStartOffsetMinutes,null,'a next-day clock must not be collapsed onto today');
assert.equal(nextDayClass.compression,false,'a date-qualified activity beyond the one-turn clock cap must not receive immediate deterministic enforcement');
assert.deepEqual(nextDayClass.suggestedAdvanceMinutes,[0,1440],'a date-qualified activity must inspect the bounded next-day window without inheriting the same-day class floor');
assert.equal(nextDayClass.boundaryLookaheadMinutes,1440,'a date-qualified activity must expose one bounded day for schedule and consequence arbitration');
assert.match(buildSceneMomentumDirective({action:'내일 10시 30분에 수업을 듣는다.',saveState:{world:{date:'1285-03-01',time:'07:40',location:'여관'}}}),/날짜 지정 시작 규칙/,'the model must be told to preserve the requested day instead of pulling the class into today');
const reachableNextDayClass=classifySceneIntent('내일 오전 1시에 수업을 듣는다.', { location:'여관',currentTime:'23:30' });
assert.equal(reachableNextDayClass.scheduledStartOffsetMinutes,90,'a next-day start inside the turn window must retain its real offset');
assert.deepEqual(reachableNextDayClass.suggestedAdvanceMinutes,[135,210],'a reachable next-day class must include its wait and natural class duration');
assert.equal(reachableNextDayClass.compression,true,'a future-date activity that fully fits inside one turn must use deterministic completion');
assert.equal(reachableNextDayClass.boundaryLookaheadMinutes,0,'a reachable future-date activity must not expand consequence arbitration beyond its valid range');
const partiallyReachableNextDayClass=classifySceneIntent('내일 오후 10시에 수업을 듣는다.', { location:'여관',currentTime:'23:30' });
assert.equal(partiallyReachableNextDayClass.scheduledStartOffsetMinutes,1350,'a future start whose minimum session fits must retain its real offset');
assert.deepEqual(partiallyReachableNextDayClass.suggestedAdvanceMinutes,[1395,1440],'only the unreachable upper end of a natural future activity range may be clamped');
assert.equal(partiallyReachableNextDayClass.compression,true,'a partially reachable future range must still enforce its earliest valid completion');
assert.equal(partiallyReachableNextDayClass.turnLimitTruncated,false,'a flexible range with a reachable lower endpoint is not an incomplete fixed request');
const startOnlyNextDayClass=classifySceneIntent('내일 오전 10시에 수업을 듣는다.', { location:'여관',currentTime:'10:30' });
assert.equal(startOnlyNextDayClass.scheduledStartOffsetMinutes,1410,'a future activity start inside the turn window must remain authoritative even when completion is outside it');
assert.deepEqual(startOnlyNextDayClass.suggestedAdvanceMinutes,[1410,1410],'a start-only future activity must stop exactly at its reachable start');
assert.equal(startOnlyNextDayClass.scheduledStartBoundaryOnly,true,'the classifier must mark a future start whose completion exceeds the turn cap');
assert.equal(startOnlyNextDayClass.turnLimitTruncated,true,'the activity must remain incomplete at its reachable start boundary');
assert.equal(startOnlyNextDayClass.compression,true,'the reachable start must use deterministic boundary enforcement');
const startOnlyDirective=buildSceneMomentumDirective({action:'내일 오전 10시에 수업을 듣는다.',saveState:{world:{date:'1285-03-01',time:'10:30',location:'여관'}}});
assert.match(startOnlyDirective,/TIME_GUIDE=1410-1410min/,'the reachable future start must replace the generic one-day guide');
assert.match(startOnlyDirective,/시작 시각에서 활동을 완료하지 않은 채 멈춘다/,'the model must stop at, rather than pass, the reachable start');
assert.match(startOnlyDirective,/시작 경계에서 미완료로 멈춘다/,'future-date guidance must agree that only the start is reachable');
assert.doesNotMatch(startOnlyDirective,/활동까지 1440분 안에 완료할 수 있다/,'future-date guidance must not contradict a start-only boundary');
const todayTerminalClass=classifySceneIntent('내일 계획을 세운 뒤 오늘 오전 10시에 수업을 듣는다.', { location:'여관',currentTime:'09:00' });
assert.equal(todayTerminalClass.dateQualifiedStart,false,'an earlier next-day planning clause must not date-qualify the terminal today activity');
assert.equal(todayTerminalClass.scheduledStartOffsetMinutes,60,'the terminal today clock must remain the selected activity start');
assert.deepEqual(todayTerminalClass.suggestedAdvanceMinutes,[105,180],'the terminal today class must retain same-day wait plus activity timing');
const immediateTrainingAfterFutureSentence=classifySceneIntent('내일 출발 예정. 지금 1시간 동안 훈련한다.', { location:'훈련장',currentTime:'09:00' });
assert.equal(immediateTrainingAfterFutureSentence.dateQualifiedStart,false,'a future date in an earlier sentence must not qualify the terminal training');
assert.deepEqual(immediateTrainingAfterFutureSentence.suggestedAdvanceMinutes,[60,60],'the terminal immediate training must retain its explicit duration');
const immediateWaitAfterFutureSentence=classifySceneIntent('내일. 지금 30분 동안 기다린다.', { location:'광장',currentTime:'09:00' });
assert.equal(immediateWaitAfterFutureSentence.dateQualifiedStart,false,'a standalone earlier future date must not qualify the terminal wait');
assert.deepEqual(immediateWaitAfterFutureSentence.suggestedAdvanceMinutes,[30,30],'the immediate wait must not become a one-day deferred action');
const topicQualifiedClass=classifySceneIntent('내일은 오전 8시에 기사과 기초 수업을 듣는다.', { location:'기숙사',currentTime:'09:00' });
assert.equal(topicQualifiedClass.dateQualifiedStart,true,'a future-day topic particle must preserve the date-qualified activity');
assert.equal(topicQualifiedClass.scheduledStartOffsetMinutes,1380,'a topic-qualified next-day start with a reachable lower range must retain its real offset');
assert.equal(topicQualifiedClass.compression,true,'a topic-qualified next-day class with a reachable lower range must enforce its start floor');
assert.deepEqual(topicQualifiedClass.suggestedAdvanceMinutes,[1425,1440]);
assert.equal(classifySceneIntent('모레는 오전 8시에 수업을 듣는다.', { location:'기숙사',currentTime:'09:00' }).dateQualifiedStart,true,'모레는 must remain a future date qualifier');
assert.equal(classifySceneIntent('정오에 수업을 듣는다.', { location:'강의실',currentTime:'09:00' }).scheduledStartOffsetMinutes,180,'noon must normalize to the same-day 12:00 start');
assert.deepEqual(classifySceneIntent('정오부터 1시까지 수업을 듣는다.', { location:'강의실',currentTime:'11:00' }).suggestedAdvanceMinutes,[120,120],'an unmarked 1 o’clock end after noon must mean the same-day afternoon');
assert.deepEqual(classifySceneIntent('정오부터 오후 1시까지 수업을 듣는다.', { location:'강의실',currentTime:'11:00' }).suggestedAdvanceMinutes,[120,120],'the inferred noon interval must match its explicit PM equivalent');
assert.equal(classifySceneIntent('자정에 훈련한다.', { location:'훈련장',currentTime:'09:00' }).scheduledStartOffsetMinutes,900,'midnight must normalize to the next upcoming 00:00 start');
assert.equal(classifySceneIntent('12시에 기사과 오리엔테이션에 참석한다.', { location:'기숙사',currentTime:'09:00' }).kind,'class-attendance','orientation attendance must use the scheduled academic profile');
const namedPcOrientation={id:'newcomer-orientation',title:'신입생 오리엔테이션',date:'1285-03-01',time:'12:00',kind:'academic',status:'scheduled'},namedPcScheduleSave={pc:{name:'카인',department:'기사과'},world:{date:'1285-03-01',time:'09:00',location:'기숙사'},scheduledEvents:[namedPcOrientation],scheduleContext:{due:[],upcoming:[namedPcOrientation]}},namedPcOrientationAction='카인이 오늘 12시에 신입생 오리엔테이션에 참석한다.';
assert.equal(isRequestedScheduledActivity(namedPcScheduleSave,namedPcOrientation,namedPcOrientationAction),true,'the saved PC subject must not prevent matching their requested schedule');
const precedingClass={id:'preceding-class',title:'기사과 기초 수업',date:'1285-03-01',time:'10:00',kind:'academic',status:'scheduled'},precedingClassSave={pc:{name:'카인',department:'기사과'},world:{date:'1285-03-01',time:'08:00',location:'기숙사'},scheduledEvents:[precedingClass],scheduleContext:{due:[],upcoming:[precedingClass]}},classThenSleep='오전 10시에 기사과 기초 수업을 듣고 8시간 동안 잠을 잔다.';
assert.equal(isRequestedScheduledActivity(precedingClassSave,precedingClass,classThenSleep),true,'an explicitly requested schedule in a preceding compound clause must not become an unrelated boundary');
assert.equal(isRequestedScheduledActivity(precedingClassSave,precedingClass,'오전 10시에 기사과 기초 수업을 듣고, 8시간 동안 잠을 잔다.'),true,'punctuation after a preceding connector must not break requested-schedule identity');
assert.equal(isRequestedScheduledActivity(precedingClassSave,precedingClass,'오전 10시에 기사과 기초 수업을 들은 후 8시간 동안 잠을 잔다.'),true,'a preceding 후 clause must remain attributable to its requested schedule');
const durationQualifiedClassAction='오전 10시에 기사과 기초 수업을 1시간 동안 듣는다.';
assert.equal(isRequestedScheduledActivity(precedingClassSave,precedingClass,durationQualifiedClassAction),true,'duration glue must not make the requested schedule look unrelated');
assert.equal(isRequestedScheduledActivity(precedingClassSave,precedingClass,'오전 10시에 기사과 기초수업을 듣는다.'),true,'Korean spacing alone must not make the requested schedule look unrelated');
const roomClass={id:'room-class',title:'101호 수업',date:'1285-03-01',time:'10:00',kind:'academic',status:'scheduled'},roomClassSave={pc:{name:'카인'},world:{date:'1285-03-01',time:'08:00',location:'기숙사'},scheduledEvents:[roomClass],scheduleContext:{due:[],upcoming:[roomClass]}},rightRoomAction='오전 10시에 101호 수업을 듣는다.',wrongRoomAction='오전 10시에 102호 수업을 듣는다.';
assert.equal(isRequestedScheduledActivity(roomClassSave,roomClass,rightRoomAction),true,'matching non-time room identifiers must preserve requested-schedule identity');
assert.equal(isRequestedScheduledActivity(roomClassSave,roomClass,wrongRoomAction),false,'a different room number must not collapse into the unique generic class fallback');
assert.equal(nextScheduleBoundaryMinutes(roomClassSave,{futureOnly:true,action:wrongRoomAction,intent:classifySceneIntent(wrongRoomAction,{currentTime:'08:00'})}),120,'the conflicting saved room schedule must remain a hard boundary');
const capitalDeparture={id:'capital-departure',title:'왕도 출발',date:'1285-03-01',time:'10:00',kind:'travel',status:'scheduled'},capitalDepartureSave={pc:{name:'카인'},world:{date:'1285-03-01',time:'08:00',location:'기숙사'},scheduledEvents:[capitalDeparture],scheduleContext:{due:[],upcoming:[capitalDeparture]}},capitalDepartureAction='오전 10시에 왕도로 간다.',capitalDepartureIntent=classifySceneIntent(capitalDepartureAction,{location:'기숙사',currentTime:'08:00',actorName:'카인'});
assert.equal(capitalDepartureIntent.kind,'travel','a requested saved departure must retain the travel profile');
assert.equal(capitalDepartureIntent.scheduledStartOffsetMinutes,120,'a requested departure must retain its saved start offset');
assert.equal(isRequestedScheduledActivity(capitalDepartureSave,capitalDeparture,capitalDepartureAction,capitalDepartureIntent),true,'a destination-matched saved departure must be recognized as the requested travel');
assert.equal(nextScheduleBoundaryMinutes(capitalDepartureSave,{futureOnly:true,action:capitalDepartureAction,intent:capitalDepartureIntent}),null,'the requested departure must not interrupt itself at its own start');
assert.doesNotMatch(buildSceneMomentumDirective({action:capitalDepartureAction,saveState:capitalDepartureSave}),/SCHEDULE_BOUNDARY=/,'the requested departure must not emit its own start as a hard boundary');
const destinationFirstCapitalAction='왕도로 오전 10시에 간다.',destinationFirstCapitalIntent=classifySceneIntent(destinationFirstCapitalAction,{location:'기숙사',currentTime:'08:00',actorName:'카인'});
assert.equal(isRequestedScheduledActivity(capitalDepartureSave,capitalDeparture,destinationFirstCapitalAction,destinationFirstCapitalIntent),true,'a saved departure must remain requested when its clock follows the destination');
assert.equal(nextScheduleBoundaryMinutes(capitalDepartureSave,{futureOnly:true,action:destinationFirstCapitalAction,intent:destinationFirstCapitalIntent}),null,'destination-first scheduled travel must not be interrupted by its own saved departure');
const overrunClassAction='3시간 동안 훈련하고 오전 10시에 기사과 기초 수업을 듣는다.',overrunClassIntent=classifySceneIntent(overrunClassAction,{location:'훈련장',currentTime:'08:00',actorName:'카인'});
assert.equal(overrunClassIntent.scheduledStartOverrun,true,'preceding work longer than the fixed start offset must be marked as an overrun');
assert.equal(overrunClassIntent.minAdvanceMinutes,120,'an overrun compound must stop at its declared terminal start');
assert.deepEqual(overrunClassIntent.suggestedAdvanceMinutes,[120,120],'an overrun compound must not include the impossible terminal activity duration');
assert.equal(isRequestedScheduledActivity(precedingClassSave,precedingClass,overrunClassAction,overrunClassIntent),false,'an impossible terminal schedule start must remain a hard boundary');
const noRowOverrunMeal=classifySceneIntent('3시간 동안 훈련하고 오전 10시에 식사를 한다.',{location:'훈련장',currentTime:'08:00'});
assert.equal(noRowOverrunMeal.scheduledStartOverrun,true,'an overrun must be detected without a saved schedule row');
assert.deepEqual(noRowOverrunMeal.suggestedAdvanceMinutes,[120,120],'a no-row overrun must still stop at the declared start');
const noRowOverrunDirective=buildSceneMomentumDirective({action:'3시간 동안 훈련하고 오전 10시에 식사를 한다.',saveState:{world:{date:'1285-03-01',time:'08:00',location:'훈련장'},scheduleContext:{due:[],upcoming:[]},scheduledEvents:[]}});
assert.match(noRowOverrunDirective,/TIME_GUIDE=120-120min/,'an overrun directive must expose only the reachable start boundary');
assert.match(noRowOverrunDirective,/앞선 행동과 뒤 활동 모두 끝나지 않은 상태로 멈춘다/,'the model must be told that neither overlapping activity completed');
assert.doesNotMatch(noRowOverrunDirective,/활동 자체의 자연 소요시간을 합친 TIME_GUIDE 안에서 완료한다/,'the ordinary scheduled-completion rule must not contradict an overrun stop');
const trainingThenAttack=classifySceneIntent('1시간 동안 훈련하고 공격한다.',{location:'훈련장',currentTime:'09:00'});
assert.equal(trainingThenAttack.kind,'committed-consequence','a terminal consequential action must remain committed after a timed prefix');
assert.equal(trainingThenAttack.compression,true,'a timed prefix before a committed consequence must remain boundary-aware');
assert.deepEqual(trainingThenAttack.suggestedAdvanceMinutes,[60,70],'the committed consequence guide must retain the exact preceding hour before its immediate resolution');
const prefixBoundary={id:'prefix-class',title:'기사과 필수 수업',date:'1285-03-01',time:'09:30',kind:'academic',status:'scheduled'},prefixBoundarySave={pc:{department:'기사과'},world:{date:'1285-03-01',time:'09:00',location:'훈련장'},scheduledEvents:[prefixBoundary],scheduleContext:{due:[],upcoming:[prefixBoundary]}};
assert.match(buildSceneMomentumDirective({action:'1시간 동안 훈련하고 공격한다.',saveState:prefixBoundarySave}),/SCHEDULE_BOUNDARY=30min/,'an intervening required schedule must stop the timed prefix before the attack');
assert.equal(classifySceneIntent('12시에 신입생 교육을 받는다.', { location:'기숙사',currentTime:'09:00' }).kind,'class-attendance','scheduled education must use the academic profile');
assert.equal(classifySceneIntent('12시에 입학식에 참석한다.', { location:'기숙사',currentTime:'09:00' }).kind,'class-attendance','entrance ceremony attendance must use the academic profile');
assert.equal(classifySceneIntent('오늘 아침 8시에 수업을 듣는다.', { location:'강의실',currentTime:'07:00' }).scheduledStartOffsetMinutes,60,'아침 must normalize to an AM clock marker');
assert.equal(classifySceneIntent('오늘 저녁 8시에 수업을 듣는다.', { location:'강의실',currentTime:'19:00' }).scheduledStartOffsetMinutes,60,'저녁 must normalize to a PM clock marker');
assert.equal(classifySceneIntent('오늘 밤 10시에 훈련한다.', { location:'훈련장',currentTime:'21:00' }).scheduledStartOffsetMinutes,60,'밤 must normalize to a PM clock marker');
assert.equal(classifySceneIntent('밤 1시에 잠을 잔다.', { location:'개인실',currentTime:'23:00' }).scheduledStartOffsetMinutes,120,'early-night clocks must roll forward to the next calendar day');
assert.equal(classifySceneIntent('내일 밤 1시에 잠을 잔다.', { location:'개인실',currentTime:'23:00' }).dateQualifiedStart,true,'a date-qualified early-night clock must preserve the requested future date');
assert.deepEqual(classifySceneIntent('밤 11시부터 밤 1시까지 잠을 잔다.', { location:'개인실',currentTime:'22:00' }).suggestedAdvanceMinutes,[180,180],'a night interval ending at 1 AM must cross midnight');
assert.deepEqual(classifySceneIntent('오후 11시부터 1시까지 잠을 잔다.', { location:'개인실',currentTime:'22:00' }).suggestedAdvanceMinutes,[180,180],'an unmarked end after a marked late-night start must roll into the next day');
assert.deepEqual(classifySceneIntent('오전 11시부터 1시까지 수업을 듣는다.', { location:'강의실',currentTime:'10:00' }).suggestedAdvanceMinutes,[180,180],'an unmarked lower hour after an AM start must resolve to the same-day afternoon');
const objectClockClass=classifySceneIntent('수업을 오전 10시에 듣는다.',{location:'강의실',currentTime:'08:00'});
assert.equal(objectClockClass.kind,'class-attendance','an object-clock-verb class must retain its academic intent');
assert.equal(objectClockClass.scheduledStartOffsetMinutes,120,'an object-clock-verb class must retain its scheduled start');
assert.deepEqual(objectClockClass.suggestedAdvanceMinutes,[165,240],'the class profile must begin after the scheduled start offset');
assert.deepEqual(classifySceneIntent('점심을 오전 10시에 먹는다.',{location:'식당',currentTime:'08:00'}).suggestedAdvanceMinutes,[140,165],'an object-clock-verb meal must retain schedule plus meal timing');
assert.deepEqual(classifySceneIntent('훈련을 오전 10시에 한다.',{location:'훈련장',currentTime:'08:00'}).suggestedAdvanceMinutes,[150,240],'an object-clock-verb training action must retain schedule plus training timing');
assert.deepEqual(classifySceneIntent('수업을 오전 10시에 두 시간 동안 듣는다.',{location:'강의실',currentTime:'08:00'}).suggestedAdvanceMinutes,[240,240],'a scheduled object-clock-verb activity must still preserve its explicit duration');
assert.deepEqual(classifySceneIntent('오전 10시부터 10시 30분까지 수업을 듣고 8시간 잠을 잔다.',{location:'개인실',currentTime:'08:00'}).suggestedAdvanceMinutes,[630,630],'a preceding clock interval must contribute its exact wait and interval length');
assert.deepEqual(classifySceneIntent('오전 10시부터 오후 1시까지 수업을 듣고 8시간 잠을 잔다.',{location:'개인실',currentTime:'08:00'}).suggestedAdvanceMinutes,[780,780],'a longer preceding clock interval must not fall back to the class range');

const sleep = classifySceneIntent('잠을 잔다.', { location:'개인실' });
assert.equal(sleep.kind, 'downtime');
assert.equal(sleep.timeProfile, 'sleep');
assert.deepEqual(sleep.suggestedAdvanceMinutes, [240, 480]);
assert.equal(classifySceneIntent('근처 여관에 방을 잡고 충분히 잠을 잔다.', { location:'중앙광장' }).timeProfile, 'sleep', 'a compressed travel-and-sleep action must retain its terminal sleep intent');
assert.equal(classifySceneIntent('아르테미스가 잠을 잔다?', { location:'개인실' }).kind, 'decision-sensitive', 'a question about sleep must not execute the described action');
assert.notEqual(classifySceneIntent('잠을 자지 않는다.', { location:'개인실' }).timeProfile, 'sleep', 'negated sleep must not become committed downtime');
assert.match(buildSceneMomentumDirective({ action:'잠을 잔다.', saveState:{ world:{ date:'1285-03-02', time:'07:20', location:'개인실' } } }), /완료 시간과 advance_minutes를 TIME_GUIDE 240-480 안에 두며/, 'completed sleep must receive explicit hard profile bounds');
assert.deepEqual(classifySceneIntent('한 시간 잠을 잔다.').suggestedAdvanceMinutes, [60, 60], 'explicit sleep duration must remain exact');
assert.deepEqual(classifySceneIntent('1시간 반 동안 잠을 잔다.').suggestedAdvanceMinutes, [90, 90], 'the half-hour suffix must add thirty minutes to an explicit hour duration');
const overlongRest=classifySceneIntent('48시간 쉰다.');
assert.equal(overlongRest.minAdvanceMinutes,1440,'a declared duration beyond one turn must cap its deterministic floor');
assert.deepEqual(overlongRest.suggestedAdvanceMinutes,[1440,1440],'an overlong declared duration must never emit a guide beyond the canonical turn limit');
assert.equal(overlongRest.turnLimitTruncated,true,'the classifier must expose that the requested activity remains unfinished at the turn limit');
const overlongDirective=buildSceneMomentumDirective({action:'48시간 쉰다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'개인실'}}});
assert.match(overlongDirective,/TIME_GUIDE=1440-1440min/,'the model guide must use the canonical one-turn maximum');
assert.match(overlongDirective,/아직 끝나지 않은 활동으로 남긴다/,'the model must stop with an overlong activity unfinished');
assert.doesNotMatch(overlongDirective,/사용자가 2880분을 직접 지정했다/,'the directive must not demand impossible one-turn completion');
const twoDayRest=classifySceneIntent('2일 동안 쉰다.');
assert.equal(twoDayRest.explicitDurationMinutes,2880,'numeric day durations must normalize to minutes');
assert.deepEqual(twoDayRest.suggestedAdvanceMinutes,[1440,1440],'a multi-day rest must stop at the canonical one-turn cap');
assert.equal(twoDayRest.turnLimitTruncated,true,'a multi-day rest must remain unfinished after one turn');
const oneDaySleep=classifySceneIntent('하루 동안 잠을 잔다.');
assert.equal(oneDaySleep.explicitDurationMinutes,1440,'하루 must normalize to one day');
assert.deepEqual(oneDaySleep.suggestedAdvanceMinutes,[1440,1440],'a one-day sleep must fit exactly at the turn cap');
assert.equal(oneDaySleep.turnLimitTruncated,false,'an exact one-day request may complete at the canonical cap');
const twoDaySleep=classifySceneIntent('이틀 동안 잠을 잔다.');
assert.equal(twoDaySleep.explicitDurationMinutes,2880,'이틀 must normalize to two days');
assert.equal(twoDaySleep.turnLimitTruncated,true,'an 이틀 sleep must remain unfinished after one turn');
const twoDayTravel=classifySceneIntent('2일 동안 수도로 간다.',{location:'중앙광장'});
assert.equal(twoDayTravel.kind,'travel','a leading day duration must retain travel intent');
assert.equal(twoDayTravel.semanticTarget,'수도','a leading day duration must not pollute the destination');
assert.equal(twoDayTravel.explicitDurationMinutes,2880,'multi-day travel must retain its declared duration');
assert.deepEqual(twoDayTravel.suggestedAdvanceMinutes,[1440,1440],'multi-day travel must stop at the one-turn cap');
assert.equal(twoDayTravel.turnLimitTruncated,true,'multi-day travel must remain incomplete at the cap');
assert.match(buildSceneMomentumDirective({action:'2일 동안 수도로 간다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'중앙광장'}}}),/아직 끝나지 않은 활동으로 남긴다/,'multi-day travel must fail closed instead of completing early');
assert.equal(classifySceneIntent('3월 1일에 훈련한다.').explicitDurationMinutes,null,'a calendar date must not become a one-day activity duration');
assert.deepEqual(classifySceneIntent('3월 1일에 훈련한다.').suggestedAdvanceMinutes,[30,120],'a calendar-dated training mention must retain the ordinary training profile');
assert.equal(classifySceneIntent('1일차 훈련을 한다.').explicitDurationMinutes,null,'an ordinal day label must not become an activity duration');
assert.deepEqual(classifySceneIntent('1일차 훈련을 한다.').suggestedAdvanceMinutes,[30,120],'an ordinal training label must retain the ordinary profile');
assert.equal(classifySceneIntent('1~2일차 훈련을 한다.').explicitDurationRangeMinutes,null,'an ordinal day range label must not become an activity duration range');
const partlyCappedRange=classifySceneIntent('12~30시간 동안 잠을 잔다.');
assert.deepEqual(partlyCappedRange.explicitDurationRangeMinutes,[720,1800],'the original explicit range must remain available for intent telemetry');
assert.equal(partlyCappedRange.minAdvanceMinutes,720,'an in-cap lower endpoint must remain a valid completion floor');
assert.deepEqual(partlyCappedRange.suggestedAdvanceMinutes,[720,1440],'only the out-of-cap upper endpoint should be clamped');
assert.equal(partlyCappedRange.turnLimitTruncated,false,'an explicit range with an in-cap endpoint is not necessarily incomplete');
const partlyCappedRangeDirective=buildSceneMomentumDirective({action:'12~30시간 동안 잠을 잔다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'개인실'}}});
assert.match(partlyCappedRangeDirective,/TIME_GUIDE=720-1440min/,'the directive must expose the valid one-turn completion range');
assert.match(partlyCappedRangeDirective,/활동 지속시간을 720-1800분으로 지정했다[\s\S]*TIME_GUIDE 720-1440분 안에서 완료한다/,'the range explanation must distinguish the original request from its in-cap guide');
assert.doesNotMatch(partlyCappedRangeDirective,/아직 끝나지 않은 활동으로 남긴다/,'the directive must not forbid completion at a valid lower endpoint');
const cappedScheduledSleep=classifySceneIntent('오늘 오후 11시에 잠을 잔다.',{location:'개인실',currentTime:'00:00'});
assert.deepEqual(cappedScheduledSleep.suggestedAdvanceMinutes,[1440,1440],'a late scheduled sleep must cap its start offset plus activity guide at one turn');
assert.equal(cappedScheduledSleep.turnLimitTruncated,true,'a scheduled activity extending beyond one turn must remain unfinished');
assert.equal(classifySceneIntent('잠깐 눈을 붙인다.').timeProfile, 'rest', 'a short-rest cue must not become a four-hour sleep floor');
assert.equal(classifySceneIntent('잠깐 대화를 하고 잠을 잔다.').timeProfile, 'sleep', 'a short cue on a preceding dialogue must not downgrade the terminal sleep action');
const scheduledSleep=classifySceneIntent('오늘 오후 10시에 잠을 잔다.', { location:'개인실',currentTime:'09:00' });
assert.equal(scheduledSleep.scheduledStartOffsetMinutes,780,'same-day scheduled sleep must retain its start offset');
assert.deepEqual(scheduledSleep.suggestedAdvanceMinutes,[1020,1260],'scheduled sleep timing must include waiting until start plus the sleep range');
const futureSleep=classifySceneIntent('내일 오전 8시에 잠을 잔다.', { location:'개인실',currentTime:'09:00' });
assert.equal(futureSleep.dateQualifiedStart,true,'next-day sleep must use future-date handling');
assert.equal(futureSleep.compression,true,'a reachable next-day sleep start must use deterministic start-boundary enforcement');
assert.equal(futureSleep.scheduledStartBoundaryOnly,true,'sleep must remain incomplete when only its next-day start fits inside one turn');
assert.deepEqual(futureSleep.suggestedAdvanceMinutes,[1380,1380]);
const scheduledWait=classifySceneIntent('오늘 오전 10시에 기다린다.', { location:'광장',currentTime:'09:00' });
assert.equal(scheduledWait.kind,'wait','a clock-qualified wait must still be recognized as committed waiting');
assert.equal(scheduledWait.scheduledStartOffsetMinutes,60);
assert.deepEqual(scheduledWait.suggestedAdvanceMinutes,[70,120],'scheduled waiting must include its start offset plus the ordinary wait range');

const withinBuilding = classifySceneIntent('A동 복도로 간다.', { location:'A동 개인실' });
assert.equal(withinBuilding.timeProfile, 'travel-within-building');
assert.deepEqual(withinBuilding.suggestedAdvanceMinutes, [2, 8]);

const campusTravel = classifySceneIntent('도서관으로 간다.', { location:'A동 개인실' });
assert.equal(campusTravel.timeProfile, 'travel-campus');
assert.deepEqual(campusTravel.suggestedAdvanceMinutes, [5, 20]);
assert.equal(classifySceneIntent('B동으로 간다.', { location:'A동 개인실' }).timeProfile, 'travel-campus');
const explicitTravel=classifySceneIntent('30분 동안 기숙사로 간다.', { location:'도서관' });
assert.equal(explicitTravel.kind,'travel');
assert.equal(explicitTravel.semanticTarget,'기숙사','the duration phrase must not pollute the travel destination');
assert.equal(explicitTravel.explicitDurationMinutes,30);
assert.deepEqual(explicitTravel.suggestedAdvanceMinutes,[30,30],'an explicit travel duration must override the natural distance range');
const destinationFirstExplicitTravel=classifySceneIntent('도서관으로 30분 동안 간다.', { location:'기숙사' });
assert.equal(destinationFirstExplicitTravel.kind,'travel','a duration between the destination and verb must preserve travel intent');
assert.equal(destinationFirstExplicitTravel.semanticTarget,'도서관','destination-first explicit travel must retain a clean semantic target');
assert.deepEqual(destinationFirstExplicitTravel.suggestedAdvanceMinutes,[30,30],'destination-first explicit travel must honor its exact duration');
const scheduledTravel=classifySceneIntent('10시에 도서관으로 간다.', { location:'A동 개인실',currentTime:'09:00' });
assert.equal(scheduledTravel.semanticTarget,'도서관','a scheduled-start clock must not pollute the travel destination');
assert.equal(scheduledTravel.scheduledStartOffsetMinutes,60,'scheduled travel must retain the wait until departure');
assert.deepEqual(scheduledTravel.suggestedAdvanceMinutes,[65,80],'scheduled travel must add the departure offset to the natural travel range');
const destinationFirstScheduledTravel=classifySceneIntent('도서관으로 10시에 간다.', { location:'A동 개인실',currentTime:'09:00' });
assert.equal(destinationFirstScheduledTravel.semanticTarget,'도서관','a trailing scheduled-start clock must not leave either the clock or destination particle in the target');
assert.deepEqual(destinationFirstScheduledTravel.suggestedAdvanceMinutes,[65,80],'travel timing must not depend on whether the destination or clock is stated first');
const markedDestinationFirstTravel=classifySceneIntent('도서관으로 오전 10시에 간다.',{location:'A동 개인실',currentTime:'08:00'});
assert.equal(markedDestinationFirstTravel.kind,'travel','a marked scheduled clock after the destination must retain travel intent');
assert.equal(markedDestinationFirstTravel.semanticTarget,'도서관','a marked post-destination clock must not pollute the destination');
assert.equal(markedDestinationFirstTravel.scheduledStartOffsetMinutes,120,'a marked post-destination clock must retain its departure offset');
assert.deepEqual(markedDestinationFirstTravel.suggestedAdvanceMinutes,[125,140],'scheduled destination-first travel must include its departure wait and natural travel time');
const nextDayTravel=classifySceneIntent('내일 10시에 도서관으로 간다.', { location:'A동 개인실',currentTime:'09:00' });
assert.equal(nextDayTravel.semanticTarget,'도서관','a future date qualifier must not pollute the travel destination');
assert.equal(nextDayTravel.compression,false,'next-day travel must not inherit a same-day deterministic travel floor');
const intervalTravel=classifySceneIntent('10시부터 11시까지 도서관으로 간다.', { location:'A동 개인실',currentTime:'09:00' });
assert.equal(intervalTravel.semanticTarget,'도서관','a clock interval must not pollute the travel destination');
assert.deepEqual(intervalTravel.suggestedAdvanceMinutes,[120,120],'a travel clock interval must end at the explicit requested clock');

const regionalTravel = classifySceneIntent('왕도로 간다.', { location:'중앙광장' });
assert.equal(regionalTravel.timeProfile, 'travel-regional');
assert.deepEqual(regionalTravel.suggestedAdvanceMinutes, [15, 60]);
assert.equal(classifySceneIntent('북쪽 숲으로 간다.', { location:'중앙광장' }).timeProfile, 'travel-regional');
assert.equal(classifySceneIntent('계산대로 간다.', { location:'식당' }).timeProfile, 'travel-local', 'a place name containing 산 must not become regional travel');
assert.deepEqual(classifySceneIntent('도서관으로 간다.').suggestedAdvanceMinutes, [3, 30], 'missing location context must preserve the proven fallback');
assert.equal(classifySceneIntent('도서관으로 내일 10시에 간다.').semanticTarget,'도서관','future-date travel must remove the destination particle after date and clock qualifiers');
assert.equal(classifySceneIntent('도로로 간다.').semanticTarget,'도로','a destination name ending in 로 must not lose part of its name');
const deferredFutureTravel=classifySceneIntent('모레 오전 10시에 왕도로 간다.',{location:'기숙사',currentTime:'09:00'});
assert.equal(deferredFutureTravel.compression,false,'future travel outside the turn window must remain deferred');
assert.equal(deferredFutureTravel.turnLimitTruncated,true,'deferred future travel must fail closed against premature arrival effects');
assert.match(buildSceneMomentumDirective({action:'모레 오전 10시에 왕도로 간다.',saveState:{world:{date:'1285-03-01',time:'09:00',location:'기숙사'}}}),/도착·이동 시작을 만들지 말고/,'deferred travel guidance must not contradict the future-date boundary');

assert.deepEqual(classifySceneIntent('1시간 동안 쉬고 8시간 동안 잠을 잔다.').suggestedAdvanceMinutes,[540,540],'동안 connectors must not be mistaken for downtime negation');
assert.deepEqual(classifySceneIntent('에밀리가 “1시간 동안 훈련하고 와”라고 말했다. 나는 8시간 동안 잠을 잔다.',{actorName:'카인'}).suggestedAdvanceMinutes,[480,480],'quoted reported work must not be totaled as a preceding player activity');
assert.deepEqual(classifySceneIntent('에밀리가 1시간 동안 훈련하고 돌아왔다. 나는 8시간 동안 잠을 잔다.',{actorName:'카인'}).suggestedAdvanceMinutes,[480,480],'an already-completed prior sentence must not be totaled into the current action');
assert.deepEqual(classifySceneIntent('에밀리가 1시간 동안 훈련하고 나는 8시간 동안 잠을 잔다.',{actorName:'카인'}).suggestedAdvanceMinutes,[480,480],'a same-sentence third-party activity must not be attributed to the player');
assert.deepEqual(classifySceneIntent('나는 1시간 동안 훈련하고 8시간 동안 잠을 잔다.',{actorName:'카인'}).suggestedAdvanceMinutes,[540,540],'a genuine first-person compound must retain its preceding activity');
const negotiationThenSleep=classifySceneIntent('협상하고 8시간 동안 잠을 잔다.',{currentTime:'09:00'});
assert.equal(negotiationThenSleep.kind,'downtime','a committed preceding negotiation must not eclipse terminal sleep intent');
assert.deepEqual(negotiationThenSleep.precedingActivityRangeMinutes,[2,10],'a preceding negotiation must retain the bounded dialogue profile');
assert.deepEqual(negotiationThenSleep.suggestedAdvanceMinutes,[482,490],'terminal sleep must include the bounded preceding negotiation and exact sleep duration');
assert.deepEqual(classifySceneIntent('훈련하고 싶지만 8시간 잠을 잔다.').suggestedAdvanceMinutes,[480,480],'desiderative training text must not become completed preceding work');
assert.deepEqual(classifySceneIntent('수업을 듣고 싶지만 8시간 잠을 잔다.').suggestedAdvanceMinutes,[480,480],'desiderative class text must not become completed preceding work');
assert.deepEqual(classifySceneIntent('30분마다 2시간 훈련한다.').suggestedAdvanceMinutes,[120,120],'a cadence duration must not be added to the declared training total');
assert.deepEqual(classifySceneIntent('30분 간격으로 2시간 훈련한다.').suggestedAdvanceMinutes,[120,120],'an interval duration must not be added to the declared training total');
assert.deepEqual(classifySceneIntent('30분씩 2시간 훈련한다.').suggestedAdvanceMinutes,[120,120],'a per-set duration must not be added to the declared training total');
const rangedCadenceTraining=classifySceneIntent('30분에서 1시간마다 3시간 훈련한다.');
assert.equal(rangedCadenceTraining.explicitDurationRangeMinutes,null,'a cadence-qualified range must not become the activity duration range');
assert.deepEqual(rangedCadenceTraining.suggestedAdvanceMinutes,[180,180],'a cadence-qualified range must leave the declared total training duration authoritative');
assert.deepEqual(classifySceneIntent('10분짜리 루틴을 1시간 동안 연습한다.').suggestedAdvanceMinutes,[60,60],'an object duration modifier must not be added to the activity duration');
assert.deepEqual(classifySceneIntent('10분에서 20분짜리 루틴을 1시간 동안 연습한다.').suggestedAdvanceMinutes,[60,60],'a ranged object duration modifier must not be added to the activity duration');
const compactHourRange=classifySceneIntent('한두 시간 동안 훈련한다.');
assert.deepEqual(compactHourRange.explicitDurationRangeMinutes,[60,120],'a colloquial compact hour range must retain both endpoints');
assert.deepEqual(compactHourRange.suggestedAdvanceMinutes,[60,120],'a colloquial compact hour range must drive the activity bounds');
assert.deepEqual(classifySceneIntent('두세 시간 동안 훈련한다.').suggestedAdvanceMinutes,[120,180],'a second colloquial compact hour range must retain both endpoints');

assert.deepEqual(classifySceneIntent('오전 10시까지 잠을 잔다.',{currentTime:'08:00'}).suggestedAdvanceMinutes,[120,120],'a single end clock must define exact remaining sleep time');
assert.deepEqual(classifySceneIntent('오전 10시까지 기다린다.',{currentTime:'08:00'}).suggestedAdvanceMinutes,[120,120],'a single end clock must define exact remaining wait time');
assert.deepEqual(classifySceneIntent('자정까지 잠을 잔다.',{currentTime:'23:00'}).suggestedAdvanceMinutes,[60,60],'a named-midnight deadline must roll to the next boundary');
assert.equal(classifySceneIntent('내일 오전 10시까지 잠을 잔다.',{currentTime:'08:00'}).turnLimitTruncated,true,'a deadline beyond one turn must preserve the 1440-minute incomplete cap');
const reachableDatedDeadline=classifySceneIntent('내일 오전 10시까지 기다린다.',{currentTime:'23:00'});
assert.equal(reachableDatedDeadline.dateQualifiedStart,false,'a dated end clock must remain a deadline rather than becoming a scheduled start');
assert.deepEqual(reachableDatedDeadline.suggestedAdvanceMinutes,[660,660],'a reachable dated deadline must use its exact elapsed interval');
assert.equal(reachableDatedDeadline.turnLimitTruncated,false,'a reachable dated deadline must complete inside the current turn limit');
const calendarClockTraining=classifySceneIntent('3월 1일 오전 10시에 훈련한다.',{currentTime:'09:00'});
assert.equal(calendarClockTraining.explicitDurationMinutes,null,'a calendar day followed by a clock must not become an activity duration');
assert.deepEqual(calendarClockTraining.suggestedAdvanceMinutes,[90,180],'the clock after a calendar date must retain normal scheduled-training timing');

const boundarySave = {
  pc:{ department:'기사과' },
  world:{ date:'1285-03-01', time:'09:40', location:'훈련장' },
  scheduleContext:{ due:[], upcoming:[{ id:'class', title:'기사과 필수 수업', date:'1285-03-01', time:'10:00', kind:'academic' }] },
};
const trainingDirective = buildSceneMomentumDirective({ action:'검술을 훈련한다.', saveState:boundarySave });
assert.match(trainingDirective, /TIME_PROFILE=training@2\.0/);
assert.match(trainingDirective, /TIME_GUIDE=30-120min/);
assert.match(trainingDirective, /SCHEDULE_BOUNDARY=20min/, 'an earlier mandatory schedule must interrupt a compressed training session');
assert.equal(scheduleBoundaryLimitMinutes(training), 30);
assert.equal(activityRangeLimitMinutes(training),120,'consequence lookahead must cover the complete valid training range');

const continueDirective = buildSceneMomentumDirective({ action:'[LUMENSIA V1.5.6 CONTINUE]', saveState:boundarySave });
assert.match(continueDirective, /CONTINUE HARD FREEZE/);
assert.doesNotMatch(continueDirective, /TIME_PROFILE=/, 'CONTINUE must not receive a new time profile');

const router = fs.readFileSync(new URL('../../api/chat-router.js', import.meta.url), 'utf8');
const health = fs.readFileSync(new URL('../../api/health.js', import.meta.url), 'utf8');
const repositoryRules = fs.readFileSync(new URL('../../AGENTS.md', import.meta.url), 'utf8');
assert.match(router, /ADAPTIVE_TIME_SCALE_VERSION/);
assert.match(router, /adaptive_time_scale_v2:true/);
assert.match(router, /mode!==['"]game['"]/, 'META/AUTO/CONTINUE must stay outside the deterministic time floor');
const contextRouter = fs.readFileSync(new URL('../../api/lib/context-router.js', import.meta.url), 'utf8');
assert.match(contextRouter, /boundaryLookahead>0\?activityRangeLimitMinutes\(sceneIntent\):0/, 'compressed timed and bounded future-date activities must expose their full valid consequence lookahead');
assert.match(contextRouter, /classifySceneIntent\(incoming\.action\|\|'',\{[^}]*actorName:save\?\.pc\?\.name\|\|''/s, 'the Director classifier must receive the canonical player name');
assert.match(health, /version:\s*'0\.8\.7'/);
assert.match(repositoryRules, /External API adapter:\s*`0\.8\.7`/, 'the authoritative release manifest must match the adapter and health surface');
assert.match(health, /adaptiveTimeScale:\s*'V2/);
assert.equal((router.match(/coreHandler\(/g) || []).length, 1, 'Adaptive Time Scale V2 must preserve one canonical core model call');

console.log('PASS Adaptive Time Scale V2 action profiles, explicit durations, travel distance, schedule priority, freeze, health, and one-call regressions');
