export default async function handler(req, res) {
  res.status(200).json({
    ok: true,
    apiConfigured: Boolean(process.env.OPENAI_API_KEY),
    luna: process.env.OPENAI_MODEL_LUNA || 'gpt-5.6-luna',
    terra: process.env.OPENAI_MODEL_TERRA || 'gpt-5.6-terra',
    accessTokenRequired: Boolean(process.env.LUMENSIA_ACCESS_TOKEN),
    promptCacheRetention: '24h',
    version: '0.8.7',
    appVersion: '1.5.6',
    adapter: '/api/chat-router',
    canonicalCore: '/api/chat',
    stablePaths: {
      runtime: '/app-runtime.js',
      api: '/api/chat-router',
      contextRouter: '/api/lib/context-router.js',
    },
    qualityPipeline: 'Single canonical pass + local runtime/QA/background',
    contextRouter: 'HF1 budgets preserved: routine 17k target / 20k soft max',
    eventDirector: 'V3 public world-result surfacing + V2.1 seeded weighted variation and NPC-goal priority',
    worldResultSurfacing: 'V1 latest confirmed public completion + plausible one-beat delivery + one bounded retry',
    livingWorld: 'V1 bounded public off-screen schedule lifecycle + explicit-completion propagation + no invented outcomes',
    npcMotivation: 'V2 evidence-gated active_goal lifecycle + progress/replacement/history + eligible-candidate Director weighting',
    relationshipReason: 'V1 cause/expression/followup + turn/source persistence',
    npcRelationship: 'V1 bounded directional NPC-to-NPC affinity/trust/status + causal history',
    factionSocialConsequence: 'V1 evidence-gated public-faction reputation + bounded causal history',
    combatGrowth: 'V2 PC-attributed evidence gates + resolution relevance + grade-aware stat/skill progress caps',
    skillLearning: 'V1 evidence-gated bounded candidates + deterministic unlock at 100 progress',
    awakeningTalentEvolution: 'V1 rare-evidence Trait/Authority candidates + milestone gates + one-step mythical talent evolution',
    sceneMomentum: 'HF1 semantic action compression + deterministic State Delta/stall + NPC initiative + meaningful-stop policy',
    adaptiveTimeScale: 'V2 action-sensitive dialogue/meal/training/class/sleep/travel time guides + schedule-boundary priority',
    timePlanParser: 'Phase 1 shadow structured clause/time plan + legacy execution authority',
    sceneOrchestration: 'V1 one primary driver + at most one causally connected secondary response + effect-only system guard',
    npcSignificance: 'V1 model-semantic foreground primary/support selection + routed canonical-key bounds + no new save root',
    knowledgeBoundaries: 'V1 owned/witnessed/told/public NPC evidence boundary + private/off-screen fail-closed provenance',
    sceneNovelty: 'V1 bounded visible-term repetition tracking + change-first suppression',
    tokenBudget: { routine: 17000, routineSoftMax: 20000, scheduled: 18000, important: 20000, critical: 24000 },
  });
}
